
<?php
$options = $block->getAttributeValue();
?>
<div class="admin__data-grid-wrap">
    <table class="data-grid" id="bms-india-report">
        <caption class="page-title">
            <?php echo __('Sales Report') ?></caption>
        <thead>
        <tr>
            <th class="data-grid-th"><span class="data-grid-cell-content"><?php echo __('Category') ?></span></th>
            <th class="data-grid-th month_1"<span class="data-grid-cell-content"><?php echo $block->getNextMonth(1)?></span></th>
            <th class="data-grid-th month_1"><span class="data-grid-cell-content"><?php echo $block->getNextMonth(2)?></span></th>
            <th class="data-grid-th month_1"><span class="data-grid-cell-content"><?php echo $block->getNextMonth(3)?></span></th>
            <th class="data-grid-th month_1"><span class="data-grid-cell-content"><?php echo $block->getNextMonth(4)?></span></th>
            <th class="data-grid-th month_1"><span class="data-grid-cell-content"><?php echo $block->getNextMonth(5)?></span></th>
            <th class="data-grid-th month_1"><span class="data-grid-cell-content"><?php echo $block->getNextMonth(6)?></span></th>
            <th class="data-grid-th month_1"><span class="data-grid-cell-content"><?php echo $block->getNextMonth(7)?></span></th>
            <th class="data-grid-th month_1"><span class="data-grid-cell-content"><?php echo $block->getNextMonth(8)?></span></th>
            <th class="data-grid-th month_1"><span class="data-grid-cell-content"><?php echo $block->getNextMonth(9)?></span></th>
            <th class="data-grid-th month_1"><span class="data-grid-cell-content"><?php echo $block->getNextMonth(10)?></span></th>
            <th class="data-grid-th month_1"><span class="data-grid-cell-content"><?php echo $block->getNextMonth(11)?></span></th>
            <th class="data-grid-th month_1"><span class="data-grid-cell-content"><?php echo $block->getNextMonth(12)?></span></th>
            <th class="data-grid-th month_1"><span class="data-grid-cell-content"><?php echo __('Total')?></span></th>
        </tr>
        </thead>
        <tbody>
            <?php
 foreach ($options as $option): ?>
        <tr>
            <td data-th="<?= $block->escapeHtml(__('category')) ?>" class="col id">
                <?php echo $option['label'] ?>
            </td>
            <td data-th="<?= $block->escapeHtml(__('month_1')) ?>" class="col id">
                <?php echo $block->getProductCount(11, $option['value']); ?>
            </td>
            <td data-th="<?= $block->escapeHtml(__('month_2')) ?>" class="col id">
                <?php echo $block->getProductCount(10, $option['value']); ?>
            </td>
            <td data-th="<?= $block->escapeHtml(__('month_3')) ?>" class="col id">
                <?php echo $block->getProductCount(9, $option['value']); ?>
            </td>
            <td data-th="<?= $block->escapeHtml(__('month_4')) ?>" class="col id">
                <?php echo $block->getProductCount(8, $option['value']); ?>
            </td>            
            <td data-th="<?= $block->escapeHtml(__('month_5')) ?>" class="col id">
                <?php echo $block->getProductCount(7, $option['value']); ?>
            </td>            
            <td data-th="<?= $block->escapeHtml(__('month_6')) ?>" class="col id">
                <?php echo $block->getProductCount(6, $option['value']); ?>
            </td>            
            <td data-th="<?= $block->escapeHtml(__('month_7')) ?>" class="col id">
                <?php echo $block->getProductCount(5, $option['value']); ?>
            </td>            
            <td data-th="<?= $block->escapeHtml(__('month_8')) ?>" class="col id">
                <?php echo $block->getProductCount(4, $option['value']); ?>
            </td>            
            <td data-th="<?= $block->escapeHtml(__('month_9')) ?>" class="col id">
                <?php echo $block->getProductCount(3, $option['value']); ?>
            </td>            
            <td data-th="<?= $block->escapeHtml(__('month_10')) ?>" class="col id">
                <?php echo $block->getProductCount(2, $option['value']); ?>
            </td>
            <td data-th="<?= $block->escapeHtml(__('month_11')) ?>" class="col id">
                <?php echo $block->getProductCount(1, $option['value']); ?>
            </td>            
            <td data-th="<?= $block->escapeHtml(__('month_12')) ?>" class="col id">
                <?php echo $block->getProductCount(0, $option['value']); ?>
            </td>            
            <td data-th="<?= $block->escapeHtml(__('total')) ?>" class="col id">
                <?php echo $block->getTotal($option['value']); ?>
            </td>
        </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
    </table>
</div>

